name: news_app_rewrite_3
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  logger: ^1.2.2
  skeletons: ^0.0.3
  gap: 2.0.1
  get: 4.6.5
  flutter_native_splash: ^2.2.19
  splashscreen: ^1.3.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

